export type Project = {
  slug: string;
  name: string;
  subtitle: string;
  problem: string;
  solution: string;
  architecture?: string;
  tech: string[];
  features: string[];
  challenges?: string;
  learned?: string;
  github: string;
  demo?: string;
  featured: boolean;
  note?: string;
};

export const projects: Project[] = [
  {
    slug: "spectrashield",
    name: "SpectraShield",
    subtitle: "Spectrogram-driven deep learning framework for synthetic voice detection",
    problem:
      "As voice-cloning and text-to-speech tools get better, telling genuine human speech apart from AI-generated audio is getting harder — and the risk of impersonation and fraud is rising with it.",
    solution:
      "SpectraShield classifies audio as real or AI-generated by converting it into Log-Mel spectrograms and running them through a CNN. Uploaded files are split into 5-second segments, each classified independently, with a majority vote deciding the final verdict. A live-microphone mode processes 4-second chunks continuously and produces a running classification. Grad-CAM overlays show which parts of the spectrogram the model focused on for each decision.",
    architecture:
      "React + Vite frontend talks to a Flask backend over REST and Socket.IO for the live-microphone stream. The backend preprocesses audio with librosa, generates 128x128 Log-Mel spectrograms, and feeds them to a custom CNN (SpectraShieldCNN) — four convolutional blocks with batch normalization and max pooling — which outputs a single fake-probability logit per chunk.",
    tech: ["Python", "PyTorch", "CNN", "Flask", "Socket.IO", "React", "Vite", "Librosa"],
    features: [
      "Chunked spectrogram classification with majority voting",
      "Grad-CAM explainability overlay per audio segment",
      "Live microphone monitoring with cumulative voting",
      "Sigmoid fake-probability scoring (FAKE at ≥ 0.30)",
    ],
    challenges:
      "Balancing responsiveness with accuracy in the live-microphone mode — early chunks carry less signal, so the system waits for five chunks (~20 seconds) before producing an initial classification rather than reacting on a single short clip.",
    learned:
      "Working end-to-end on this project meant going deeper into audio preprocessing (spectrogram generation, chunking strategy) and model interpretability (Grad-CAM) than typical coursework covers, plus wiring a PyTorch model into a real-time Flask/Socket.IO service.",
    github: "https://github.com/prakashss15/SpectraShield",
    featured: true,
    note: "Built as part of a team project, extended from a shared team codebase.",
  },
  {
    slug: "mj-spectra-shield",
    name: "Real-Time Deepfake Audio Detection",
    subtitle: "CNN-based system for classifying live and uploaded audio as real or synthetic",
    problem:
      "Text-to-speech and voice-cloning technology can generate highly realistic synthetic audio, opening the door to impersonation, fraud, and misinformation — while most detection needs to work on both live streams and uploaded files, with results a person can actually trust.",
    solution:
      "This system extracts Log-Mel spectrogram features from audio and classifies them with a convolutional neural network, returning a confidence score alongside the real/fake verdict. It supports both live microphone input and pre-recorded file uploads, and pairs classification with explainability visualizations (Grad-CAM / saliency maps) so the decision isn't a black box.",
    architecture:
      "A React.js frontend communicates with a FastAPI backend that handles audio ingestion, preprocessing (librosa, NumPy, SciPy), spectrogram feature extraction, CNN inference, and explainability generation, returning a confidence-scored classification.",
    tech: ["Python", "FastAPI", "React", "PyTorch", "CNN", "Librosa", "NumPy", "Grad-CAM"],
    features: [
      "Live microphone streaming and file-upload analysis",
      "Log-Mel spectrogram feature extraction",
      "Grad-CAM / saliency-based explainability",
      "Confidence-scored real/fake classification",
    ],
    learned:
      "This project reinforced the same audio-ML pipeline from a different angle — a FastAPI backend instead of Flask, and a stronger focus on presenting model confidence and explainability to the end user.",
    github: "https://github.com/prakashss15/MJ-Spectra-Sheild",
    featured: true,
  },
  {
    slug: "smart-logistics",
    name: "Smart Logistics",
    subtitle: "Vehicle route management system for fleet tracking and ETA prediction",
    problem:
      "Fleet operators moving vehicles across highway networks need real-time visibility into where vehicles are, whether they've deviated from their planned route, and when they'll actually arrive.",
    solution:
      "A Flask application that locates vehicles traveling between cities, flags off-route vehicles using GPS/IMU/RF signal analysis, computes optimized routes through OSRM with automatic fallback routing, and predicts arrival times with a trained Random Forest model. Results are shown on a live Leaflet.js dashboard, alongside CO₂ tracking for fleet sustainability.",
    architecture:
      "The Flask API separates concerns into dedicated modules — deviation detection, route optimization, and ML-based ETA prediction — with models serialized via joblib and data persisted locally in CSV files, so the system runs without an external database.",
    tech: ["Python", "Flask", "scikit-learn", "Pandas", "Leaflet.js", "OSRM", "Geopy"],
    features: [
      "Vehicle discovery between specified cities",
      "GPS/IMU/RF-based route deviation monitoring",
      "OSRM route optimization with fallback routing",
      "Random Forest ETA prediction",
      "Live interactive fleet dashboard with CO₂ metrics",
    ],
    learned:
      "Combining a rule-based deviation detector with a learned ETA model in the same service required thinking carefully about where to draw the line between heuristics and machine learning.",
    github: "https://github.com/prakashss15/smart-logistics",
    featured: true,
  },
  {
    slug: "factory-management",
    name: "Factory Inventory & Workforce Management",
    subtitle: "Full-stack system for factory inventory and workforce management",
    problem:
      "Manufacturing operations need a single system to track inventory and manage workforce data instead of juggling spreadsheets across teams.",
    solution:
      "A full-stack application structured around separate backend, frontend, and database layers, built to streamline factory inventory tracking and workforce management for manufacturing operations.",
    tech: ["JavaScript", "HTML", "CSS"],
    features: ["Inventory tracking", "Workforce management", "Separated backend/frontend/database architecture"],
    github: "https://github.com/prakashss15/Factory-Management",
    featured: true,
  },
  {
    slug: "online-quiz-system",
    name: "Online Quiz System",
    subtitle: "Django platform for timed, auto-evaluated assessments",
    problem:
      "Instructors need a way to run timed assessments at scale, assign them to the right students, and get results back without manually grading every attempt.",
    solution:
      "A Django-based platform where instructors create timed quizzes, assign them by year/branch/section, and get automatic evaluation with leaderboards and per-student results. Students get randomized question order per attempt, optional access codes, and tab-switch detection to support test integrity.",
    tech: ["Python", "Django", "SQLite"],
    features: [
      "Separate teacher and student authentication flows",
      "Timed, auto-evaluated quiz attempts with randomized ordering",
      "Leaderboards and individual result tracking",
      "CSV export for instructors",
      "Tab-switch detection during attempts",
    ],
    github: "https://github.com/prakashss15/Online-Quiz-System",
    featured: true,
  },
  {
    slug: "industrial-anomaly-detection",
    name: "Industrial Anomaly Detection",
    subtitle: "AI-integrated framework for industrial machine accident prediction",
    problem:
      "Manufacturing environments benefit from catching equipment anomalies before they turn into accidents or downtime.",
    solution:
      "An AI-integrated framework aimed at predicting industrial machine accidents using machine learning models, applied to manufacturing environments.",
    tech: ["Machine Learning", "HTML"],
    features: ["ML-based anomaly/accident prediction for industrial machinery"],
    github: "https://github.com/prakashss15/industrial-anamoly-detection",
    featured: false,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export type MiniRepo = {
  name: string;
  description: string;
  language: string;
  github: string;
};

export const moreRepos: MiniRepo[] = [
  {
    name: "Tony-Stark--The-Iron-Legacy",
    description:
      "Interactive, HUD-inspired digital portfolio concept covering the technologies and suit progression from the Iron Man universe.",
    language: "HTML",
    github: "https://github.com/prakashss15/Tony-Stark--The-Iron-Legacy",
  },
  {
    name: "QR-code-generator",
    description: "QR code generation utility for URLs.",
    language: "Python",
    github: "https://github.com/prakashss15/QR-code-generator",
  },
  {
    name: "Card-Magic-Trick-Game-",
    description: "Number prediction game based on a classic card magic trick.",
    language: "C++",
    github: "https://github.com/prakashss15/Card-Magic-Trick-Game-",
  },
  {
    name: "Qphi",
    description: "JavaScript project exploring web application development.",
    language: "JavaScript",
    github: "https://github.com/prakashss15/Qphi",
  },
  {
    name: "resto01",
    description: "TypeScript web application project.",
    language: "TypeScript",
    github: "https://github.com/prakashss15/resto01",
  },
  {
    name: "djangolabs",
    description: "Django framework practice and experiments.",
    language: "Python",
    github: "https://github.com/prakashss15/djangolabs",
  },
];
